server:
  port: 9527
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - After=2021-09-15T10:10:26.296+08:00[Asia/Shanghai]
            - Cookie=username,atguigu

        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/create   #断言,路径相匹配的进行路由
