server:
  port: 8081
spring:
  application:
    name: rediscache
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: xxxx
    password: xxxx
  redis:
    host: xxxx
    port: 6379
    password: xxxx
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: cn.kingshin.rediscache.entity # 别名扫描包
logging:
  level:
    cn.kingshin.rediscache: debug
# redission
