### 查询服务
GET http://127.0.0.1:19001/imooc/emall-nacos-client/nacos-client/service-instance?serviceId=emall-gateway
Accept: application/json
emall-user: eyJhbGciOiJSUzI1NiJ9.eyJlbWFsbC11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJjaGloc2llbkBmb3guY29tXCJ9IiwianRpIjoiNTU4MDIwYzgtN2M1YS00MGU0LTkwNGItNWMxMzVhODZhNTdmIiwiZXhwIjoxNjYyNjUyODAwfQ.Y9Ngq4vybaPKd2jqbejmnrOdQ8mB0jMm30Go8BUtVvPsC0QVDO-zBQUFZXvyDOLWRpr27WekJQ0NM-2k6PfEamJ88aSz4cUUDhO7NdSogrS4RpDPdjSSQKKBYuRitZ6r6LB9L5vCjXM8pZe3wALcwh1TphJGoOORJX2uw7zDXkoDHQxdEGzeXjXGwY9fwSrPFGKyWqdy786mPBmeqRyWuXH4_HLgRmWjYMpDffy4kTzrD8Qw1HNY2jAdKtZvT32mVTkDJZRVDNy5I1X0T0Lfua0F46fSTV60Uvh0ZQm27FEQmklR6zMzKVcnNwsJBiSwF_Vx0-sCaVJZ6T1SHpAQTw
token: imooc
