### 查询服务
GET http://127.0.0.1:19001/imooc/emall-nacos-client/nacos-client/service-instance?serviceId=emall-gateway
Accept: application/json
emall-user: eyJhbGciOiJSUzI1NiJ9.eyJlbWFsbC11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJjaGloc2llbkBmb3guY29tXCJ9IiwianRpIjoiYTIzNTNkMGItMjJiYS00OTE1LWI1M2MtNmRjODVmMDY0YTlhIiwiZXhwIjoxNjYyNTY2NDAwfQ.QEGlMy42jVNThOYeiSNDPh7Z5wLQFHu9CgmSU_CvZzdC5mP8OM6nRYMhq_lCfArVucBjh92tHpv5vZApNPYwY1hybe5NpGM-qa6NmD4VeC4lJMDihA5n-PnNrglNsatUrXm1cR_D9tBHo86PDQXOkiRkR-9uvYLsw_JJD6dnLhQjdpwHBD16JS6vbx6P96TUVCXGNOLmisEEoO-ayTwJzDGuzCbwYJxCkqPSDbXkBXGomBuftPg4YpnxLXiOVnf7tR9-IA8HmuCJwhvWilFAm2AP7AdekYwAqTseXsc5MfbQ5d6birQYSIIQHfw-OyDNztbB19x2woLSluTIV4zz5A
token: imooc
