spring:
  cloud:
    nacos:
     discovery:
      #如果是nacos集群环境则指向nginx的地址+端(80端口可以省略)
      server-addr: localhost:8848
      #同一个项目下的服务，要在同一个分组下，相互间才能通信
      group: TEST_GROUP
	    namespace: springboot


#nacos:
#  discovery:
#    server-addr: 139.155.39.21:8848
#    username: nacos
#    password: nacos
#    auto-register: true
#    register:
#      enabled: true
#      service-name: nacos-producer-service
#      group-name: DEFAULT_GROUP
#  config:
#    server-addr: 139.155.39.21:8848
#    username: nacos
#    password: nacos
#    namespace: 4cac91eb-ccbe-467e-89ea-c1a9a2a62ece
#    data-id: nacos-producer-dev.yaml
#    auto-refresh: true
#    group: TEST_GROUP
#    type: yaml
#    bootstrap:
#      enable: true
#      log-enable: true