### 获取当前用户余额信息
GET http://127.0.0.1:19001/imooc/emall-account-service/balance/current-balance
Accept: application/json
emall-user: eyJhbGciOiJSUzI1NiJ9.eyJlbWFsbC11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJjaGloc2llbkBmb3guY29tXCJ9IiwianRpIjoiMGJjYmMxOWUtNWUxZS00YjRmLTgwMzMtMDE5Y2RhNDQzZDc5IiwiZXhwIjoxNjYyOTEyMDAwfQ.Ai6hvDm4x93Gs4kWCphht1GfsIGstIQLiNuF4OJNX4tYd8zIQWThWp2vAHlN085jjnzzXuslSizul1km40rM39CP5OzMhGGeeYQ6jKPZ3n5OBIf00Ke1IRg5k2-6qG_4UZoWylnutOE8dRngB89-bnGp5Y8DoT3-gwBfKHPaWEFbJnOAwIvwpUuyxe0jH7CPg4tLTXqykJkgGIGAca6vS6Yqk35iWkbdVsH5uh0sOxnU3PV4SjkoWXXwQqrBrxakFW5fRdnubobQlWF_zKoY8c-fV816xXY8ujVMnx4sAH5BlGwMMyDI81FoRPi72SFvRoioytaQQAIOs_mDATWdbA

### 扣减用户余额
PUT http://127.0.0.1:19001/imooc/emall-account-service/balance/deduct-balance
Content-Type: application/json
emall-user: eyJhbGciOiJSUzI1NiJ9.eyJlbWFsbC11c2VyIjoie1wiaWRcIjoxMCxcInVzZXJuYW1lXCI6XCJjaGloc2llbkBmb3guY29tXCJ9IiwianRpIjoiMGJjYmMxOWUtNWUxZS00YjRmLTgwMzMtMDE5Y2RhNDQzZDc5IiwiZXhwIjoxNjYyOTEyMDAwfQ.Ai6hvDm4x93Gs4kWCphht1GfsIGstIQLiNuF4OJNX4tYd8zIQWThWp2vAHlN085jjnzzXuslSizul1km40rM39CP5OzMhGGeeYQ6jKPZ3n5OBIf00Ke1IRg5k2-6qG_4UZoWylnutOE8dRngB89-bnGp5Y8DoT3-gwBfKHPaWEFbJnOAwIvwpUuyxe0jH7CPg4tLTXqykJkgGIGAca6vS6Yqk35iWkbdVsH5uh0sOxnU3PV4SjkoWXXwQqrBrxakFW5fRdnubobQlWF_zKoY8c-fV816xXY8ujVMnx4sAH5BlGwMMyDI81FoRPi72SFvRoioytaQQAIOs_mDATWdbA

{
  "userId": 10,
  "balance": 2000
}
